cmds.shadingNode('setRange',au=1,n='sr_footroll_l')
cmds.shadingNode('plusMinusAverage',au=1,n='pm_footroll_l')
cmds.shadingNode('setRange',au=1,n='sr_footroll_r')
cmds.shadingNode('plusMinusAverage',au=1,n='pm_footroll_r')
cmds.setAttr("rig_ankle_l_pivToes.rx", lock=0)
cmds.setAttr("rig_ankle_r_pivToes.rx", lock=0)
cmds.connectAttr ('ctrl_hip_l_ik.FootRoll', 'sr_footroll_l.valueX',f=1)
cmds.connectAttr ('ctrl_hip_r_ik.FootRoll', 'sr_footroll_r.valueX',f=1)
cmds.connectAttr ('pm_footroll_l.output1D', 'rig_ankle_l_pivToes.rotateX',f=1)
cmds.connectAttr ('pm_footroll_r.output1D', 'rig_ankle_r_pivToes.rotateX',f=1)
#cmds.connectAttr ('pm_footroll_l.output1D', 'ctrl_hip_l_ik.ToeBend')
#cmds.connectAttr ('pm_footroll_r.output1D', 'ctrl_hip_r_ik.ToeBend')
cmds.connectAttr ('sr_footroll_r.outValueX', 'pm_footroll_r.input1D[0]',f=1)
cmds.connectAttr ('sr_footroll_l.outValueX', 'pm_footroll_l.input1D[0]',f=1)
cmds.connectAttr ('ctrl_hip_l_ik.ToeBend', 'pm_footroll_l.input1D[1]',f=1)
cmds.connectAttr ('ctrl_hip_r_ik.ToeBend', 'pm_footroll_r.input1D[1]',f=1)
cmds.setAttr("rig_ankle_l_pivToes.rx", lock=1)
cmds.setAttr("rig_ankle_r_pivToes.rx", lock=1)