setAttr("net_Spine.fCtrlSize", .1)
setAttr("net_FK5.fCtrlSize", .05)
setAttr("net_FK.fCtrlSize", .05)
setAttr("net_FK1.fCtrlSize", .05)
setAttr("net_FK2.fCtrlSize", .05)
setAttr("net_FK3.fCtrlSize", .05)
setAttr("net_FK4.fCtrlSize", .05)
setAttr("net_FaceEyes.fCtrlOffset",.5)
setAttr("net_FaceEyes.fCtrlSize",.1)
setAttr("net_Arm1.fCtrlSize",0.08)
setAttr("net_Arm.fCtrlSize",0.08)
setAttr("net_Hand1.fCtrlSize",0.018)
setAttr("net_Hand.fCtrlSize",0.018)
setAttr("net_Leg1.fCtrlSize",.1)
setAttr("net_Leg.fCtrlSize",.1)
setAttr("net_RigRoot_.fCtrlSize",.1)